
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 02 13:09:47 CST 2018
//----------------------------------------------------

package compi201503600.analisis.java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 48;
  public static final int STRING_LITERAL = 4;
  public static final int TBOOLEAN = 47;
  public static final int TCHAR = 49;
  public static final int ARGS = 69;
  public static final int ENTERO = 67;
  public static final int OPMAY = 27;
  public static final int CASE = 58;
  public static final int PRIVATE = 37;
  public static final int PARENIZQ = 5;
  public static final int LLAVEDER = 10;
  public static final int OPINCREMENT = 24;
  public static final int OUT = 63;
  public static final int FOR = 54;
  public static final int OPMENIGUAL = 28;
  public static final int STATIC = 65;
  public static final int MULTIGUAL = 18;
  public static final int OPSUMA = 19;
  public static final int CORCHIZQ = 7;
  public static final int IGUAL = 15;
  public static final int MASIGUAL = 16;
  public static final int OPDECREMENT = 25;
  public static final int TDOUBLE = 50;
  public static final int MAIN = 66;
  public static final int IF = 52;
  public static final int THIS = 42;
  public static final int ID = 2;
  public static final int DECIMAL = 68;
  public static final int EOF = 0;
  public static final int SYSTEM = 62;
  public static final int RETURN = 61;
  public static final int OPDISTINTO = 31;
  public static final int CLASE = 41;
  public static final int OPNOT = 34;
  public static final int OPAND = 32;
  public static final int OPOR = 33;
  public static final int NEW = 43;
  public static final int error = 1;
  public static final int TOBJECT = 51;
  public static final int COMA = 13;
  public static final int COMENTARIO = 3;
  public static final int NULL = 44;
  public static final int BREAK = 60;
  public static final int PARENDER = 6;
  public static final int OPDIV = 22;
  public static final int TVOID = 45;
  public static final int SWITCH = 57;
  public static final int PCOMA = 11;
  public static final int OPRESTA = 20;
  public static final int TINT = 46;
  public static final int ELSE = 53;
  public static final int PROTECTED = 39;
  public static final int PUNTO = 14;
  public static final int CORCHDER = 8;
  public static final int PACKAGE = 35;
  public static final int WHILE = 55;
  public static final int FINAL = 40;
  public static final int MENIGUAL = 17;
  public static final int LLAVEIZQ = 9;
  public static final int DEFAULT = 59;
  public static final int OPIGUAL = 30;
  public static final int PUBLIC = 38;
  public static final int DPUNTOS = 12;
  public static final int IMPORTA = 36;
  public static final int OPMAYIGUAL = 29;
  public static final int OPMODULO = 23;
  public static final int OPMULT = 21;
  public static final int OPMEN = 26;
  public static final int PRINT = 64;
  public static final int DO = 56;
}

