
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 29 16:14:43 CST 2018
//----------------------------------------------------

package compi201503600.analisis.json;

import java_cup.runtime.*;
import java.io.FileReader;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Mar 29 16:14:43 CST 2018
  */
public class ScannerSintaxJson extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ScannerSintaxJson() {super();}

  /** Constructor which sets the default scanner. */
  public ScannerSintaxJson(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ScannerSintaxJson(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\003\000\002\002\004\000\002\003" +
    "\005\000\002\003\004\000\002\004\005\000\002\004\003" +
    "\000\002\005\007\000\002\005\007\000\002\005\007\000" +
    "\002\005\007\000\002\005\007\000\002\005\004\000\002" +
    "\006\003\000\002\006\003\000\002\007\003\000\002\007" +
    "\002\000\002\010\005\000\002\010\003\000\002\011\007" +
    "\000\002\011\004\000\002\012\003\000\002\012\002\000" +
    "\002\013\005\000\002\013\003\000\002\014\005\000\002" +
    "\014\004\000\002\015\005\000\002\015\003\000\002\016" +
    "\005\000\002\016\005\000\002\016\005\000\002\016\005" +
    "\000\002\017\003\000\002\017\002\000\002\020\005\000" +
    "\002\020\003\000\002\021\005\000\002\021\004\000\002" +
    "\022\005\000\002\022\003\000\002\023\005\000\002\023" +
    "\005\000\002\023\005\000\002\024\003\000\002\024\002" +
    "\000\002\025\005\000\002\025\003\000\002\026\007\000" +
    "\002\026\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\154\000\006\003\004\004\005\001\002\000\004\005" +
    "\156\001\002\000\016\003\012\012\016\013\013\014\015" +
    "\015\017\016\020\001\002\000\004\002\010\001\002\000" +
    "\004\002\001\001\002\000\004\002\000\001\002\000\006" +
    "\005\154\011\153\001\002\000\004\007\152\001\002\000" +
    "\004\010\133\001\002\000\006\005\ufffc\011\ufffc\001\002" +
    "\000\004\010\077\001\002\000\004\010\071\001\002\000" +
    "\004\010\040\001\002\000\004\010\021\001\002\000\004" +
    "\006\022\001\002\000\010\003\025\004\026\007\uffd5\001" +
    "\002\000\006\007\uffd3\011\uffd3\001\002\000\006\007\uffd6" +
    "\011\036\001\002\000\004\005\035\001\002\000\004\024" +
    "\031\001\002\000\004\007\030\001\002\000\006\005\ufff7" +
    "\011\ufff7\001\002\000\004\010\032\001\002\000\004\030" +
    "\033\001\002\000\004\005\034\001\002\000\006\007\uffd2" +
    "\011\uffd2\001\002\000\006\007\uffd1\011\uffd1\001\002\000" +
    "\006\003\025\004\026\001\002\000\006\007\uffd4\011\uffd4" +
    "\001\002\000\004\006\041\001\002\000\010\003\042\004" +
    "\043\007\uffe0\001\002\000\004\005\070\001\002\000\010" +
    "\017\054\020\056\023\053\001\002\000\004\007\051\001" +
    "\002\000\006\007\uffde\011\uffde\001\002\000\006\007\uffe1" +
    "\011\047\001\002\000\006\003\042\004\043\001\002\000" +
    "\006\007\uffdf\011\uffdf\001\002\000\006\005\ufff8\011\ufff8" +
    "\001\002\000\006\005\066\011\065\001\002\000\004\010" +
    "\063\001\002\000\004\010\061\001\002\000\006\005\uffda" +
    "\011\uffda\001\002\000\004\010\057\001\002\000\004\030" +
    "\060\001\002\000\006\005\uffd8\011\uffd8\001\002\000\004" +
    "\030\062\001\002\000\006\005\uffd9\011\uffd9\001\002\000" +
    "\004\030\064\001\002\000\006\005\uffd7\011\uffd7\001\002" +
    "\000\010\017\054\020\056\023\053\001\002\000\006\007" +
    "\uffdd\011\uffdd\001\002\000\006\005\uffdb\011\uffdb\001\002" +
    "\000\006\007\uffdc\011\uffdc\001\002\000\004\006\072\001" +
    "\002\000\006\025\075\026\074\001\002\000\004\007\076" +
    "\001\002\000\004\007\ufff4\001\002\000\004\007\ufff5\001" +
    "\002\000\006\005\ufffb\011\ufffb\001\002\000\004\006\100" +
    "\001\002\000\010\003\102\004\104\007\uffec\001\002\000" +
    "\006\007\uffed\011\131\001\002\000\004\005\130\001\002" +
    "\000\004\007\127\001\002\000\012\017\111\020\112\021" +
    "\107\022\113\001\002\000\006\007\uffea\011\uffea\001\002" +
    "\000\006\005\uffe6\011\uffe6\001\002\000\004\010\125\001" +
    "\002\000\006\005\123\011\122\001\002\000\004\010\120" +
    "\001\002\000\004\010\116\001\002\000\004\010\114\001" +
    "\002\000\004\030\115\001\002\000\006\005\uffe2\011\uffe2" +
    "\001\002\000\004\030\117\001\002\000\006\005\uffe4\011" +
    "\uffe4\001\002\000\004\030\121\001\002\000\006\005\uffe5" +
    "\011\uffe5\001\002\000\012\017\111\020\112\021\107\022" +
    "\113\001\002\000\006\007\uffe9\011\uffe9\001\002\000\006" +
    "\005\uffe7\011\uffe7\001\002\000\004\030\126\001\002\000" +
    "\006\005\uffe3\011\uffe3\001\002\000\006\005\ufff9\011\ufff9" +
    "\001\002\000\006\007\uffe8\011\uffe8\001\002\000\006\003" +
    "\102\004\104\001\002\000\006\007\uffeb\011\uffeb\001\002" +
    "\000\004\006\134\001\002\000\010\003\140\004\141\007" +
    "\ufff2\001\002\000\004\007\151\001\002\000\006\007\ufff3" +
    "\011\147\001\002\000\006\007\ufff0\011\ufff0\001\002\000" +
    "\004\005\146\001\002\000\004\017\142\001\002\000\004" +
    "\010\143\001\002\000\004\030\144\001\002\000\004\005" +
    "\145\001\002\000\006\007\uffef\011\uffef\001\002\000\006" +
    "\007\uffee\011\uffee\001\002\000\006\003\140\004\141\001" +
    "\002\000\006\007\ufff1\011\ufff1\001\002\000\006\005\ufffa" +
    "\011\ufffa\001\002\000\006\005\ufff6\011\ufff6\001\002\000" +
    "\016\003\012\012\016\013\013\014\015\015\017\016\020" +
    "\001\002\000\004\002\uffff\001\002\000\006\005\ufffd\011" +
    "\ufffd\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\154\000\006\002\005\003\006\001\001\000\002\001" +
    "\001\000\006\004\010\005\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\024\026\025\023\026\022" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\026\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\017\043\020" +
    "\045\021\044\001\001\000\002\001\001\000\006\022\051" +
    "\023\054\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\023\066" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\072\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\012\102\013\100\014\104" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\107\016\105\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\016\123" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\131\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\134\010\135\011\136\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\147\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\154\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ScannerSintaxJson$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ScannerSintaxJson$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ScannerSintaxJson$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


//Codigo visible

    public void syntax_error(Symbol s){
        System.out.println("Error R de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error NR de sintaxis: "+ s.value +" Linea "+(s.left+1)+" columna "+(s.right+1) );
    }

    /* Reporte de error encontrado. */
    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" in line "+(s.left+1));
                if (s.right >= 0)
                    m.append(", column "+(s.right+1));
            }
        }
        m.append(" : "+message);
        System.err.println(m);
    }
   
    /* Cuando se encuentra un error de donde el sistema no puede
        recuperarse, se lanza un error fatal. Se despliega el mensaje
        de error y se finaliza la ejecucion. */
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

    /* Metodo main para garantizar la ejecucion del analizador
       lexico y sintactico, ademas que se pase como parametro la tabla
       de simbolos correspondiente. */
    public static void main(String[] args){
        try {
            ScannerSintaxJson asin = new ScannerSintaxJson(
                    new ScannerLexJson( new FileReader(args[0])));
            Object result = asin.parse().value;
            System.out.println("\n*** Resultados finales ***");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ScannerSintaxJson$actions {



  private final ScannerSintaxJson parser;

  /** Constructor */
  CUP$ScannerSintaxJson$actions(ScannerSintaxJson parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ScannerSintaxJson$do_action(
    int                        CUP$ScannerSintaxJson$act_num,
    java_cup.runtime.lr_parser CUP$ScannerSintaxJson$parser,
    java.util.Stack            CUP$ScannerSintaxJson$stack,
    int                        CUP$ScannerSintaxJson$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ScannerSintaxJson$result;

      /* select the action based on the action number */
      switch (CUP$ScannerSintaxJson$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // SENTCOMMENT ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTCOMMENT",20, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // SENTCOMMENT ::= LLAVEIZQ TEXTO DPUNTOS CADENA LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTCOMMENT",20, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // SENTSCOMMENT ::= SENTCOMMENT 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCOMMENT",19, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // SENTSCOMMENT ::= SENTSCOMMENT COMA SENTCOMMENT 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCOMMENT",19, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // SENTSCOMMENTS ::= 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCOMMENTS",18, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // SENTSCOMMENTS ::= SENTSCOMMENT 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCOMMENTS",18, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // PARAMMET ::= PARAMETROS DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMMET",17, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // PARAMMET ::= TIPO DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMMET",17, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // PARAMMET ::= NOMBRE DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMMET",17, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // PARAMSMET ::= PARAMMET 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMSMET",16, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // PARAMSMET ::= PARAMSMET COMA PARAMMET 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMSMET",16, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // SENTMET ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTMET",15, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // SENTMET ::= LLAVEIZQ PARAMSMET LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTMET",15, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // SENTSMET ::= SENTMET 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSMET",14, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // SENTSMET ::= SENTSMET COMA SENTMET 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSMET",14, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // SENTSMETODOS ::= 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSMETODOS",13, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // SENTSMETODOS ::= SENTSMET 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSMETODOS",13, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PARAMVAR ::= CLASE DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMVAR",12, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PARAMVAR ::= FUNCION DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMVAR",12, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // PARAMVAR ::= TIPO DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMVAR",12, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // PARAMVAR ::= NOMBRE DPUNTOS CADENA 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMVAR",12, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // PARAMSVAR ::= PARAMVAR 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMSVAR",11, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // PARAMSVAR ::= PARAMSVAR COMA PARAMVAR 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("PARAMSVAR",11, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // SENTVAR ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTVAR",10, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // SENTVAR ::= LLAVEIZQ PARAMSVAR LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTVAR",10, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // SENTSVAR ::= SENTVAR 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSVAR",9, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // SENTSVAR ::= SENTSVAR COMA SENTVAR 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSVAR",9, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // SENTSVARS ::= 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSVARS",8, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SENTSVARS ::= SENTSVAR 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSVARS",8, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // SENTCLASES ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTCLASES",7, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SENTCLASES ::= LLAVEIZQ NOMBRE DPUNTOS CADENA LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTCLASES",7, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SENTSCLASES ::= SENTCLASES 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCLASES",6, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTSCLASES ::= SENTSCLASES COMA SENTCLASES 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCLASES",6, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTSCLASS ::= 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCLASS",5, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTSCLASS ::= SENTSCLASES 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSCLASS",5, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTSSCORE ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSSCORE",4, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTSSCORE ::= ENTERO 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSSCORE",4, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTJSON ::= error CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTJSON ::= COMENTARIOS DPUNTOS CORCHIZQ SENTSCOMMENTS CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTJSON ::= METODOS DPUNTOS CORCHIZQ SENTSMETODOS CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTJSON ::= VARIABLES DPUNTOS CORCHIZQ SENTSVARS CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // SENTJSON ::= CLASES DPUNTOS CORCHIZQ SENTSCLASS CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SENTJSON ::= SCORE DPUNTOS CORCHIZQ SENTSSCORE CORCHDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTJSON",3, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-4)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // SENTSJSON ::= SENTJSON 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSJSON",2, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // SENTSJSON ::= SENTSJSON COMA SENTJSON 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("SENTSJSON",2, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INICIO ::= error LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("INICIO",1, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= LLAVEIZQ SENTSJSON LLAVEDER 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("INICIO",1, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-2)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= S0 EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)).value;
		RESULT = start_val;
              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.elementAt(CUP$ScannerSintaxJson$top-1)), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ScannerSintaxJson$parser.done_parsing();
          return CUP$ScannerSintaxJson$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // S0 ::= INICIO 
            {
              Object RESULT =null;

              CUP$ScannerSintaxJson$result = parser.getSymbolFactory().newSymbol("S0",0, ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScannerSintaxJson$stack.peek()), RESULT);
            }
          return CUP$ScannerSintaxJson$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

