
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 29 16:14:43 CST 2018
//----------------------------------------------------

package compi201503600.analisis.json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 22;
  public static final int METODOS = 11;
  public static final int DECIMAL = 20;
  public static final int SCORE = 8;
  public static final int ID = 21;
  public static final int CLASE = 16;
  public static final int TIPO = 14;
  public static final int LLAVEIZQ = 2;
  public static final int VARIABLES = 10;
  public static final int COMA = 7;
  public static final int COMENTARIOS = 12;
  public static final int LLAVEDER = 3;
  public static final int NOMBRE = 13;
  public static final int EOF = 0;
  public static final int PARAMETROS = 17;
  public static final int CORCHIZQ = 4;
  public static final int TEXTO = 18;
  public static final int CORCHDER = 5;
  public static final int error = 1;
  public static final int CLASES = 9;
  public static final int ENTERO = 19;
  public static final int DPUNTOS = 6;
  public static final int FUNCION = 15;
}

