
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 02 22:58:31 CST 2018
//----------------------------------------------------

package compi201503600.analisis.json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 4;
  public static final int METODOS = 15;
  public static final int DECIMAL = 3;
  public static final int SCORE = 12;
  public static final int CLASE = 20;
  public static final int ID = 5;
  public static final int TIPO = 18;
  public static final int LLAVEIZQ = 6;
  public static final int VARIABLES = 14;
  public static final int COMA = 11;
  public static final int COMENTARIOS = 16;
  public static final int LLAVEDER = 7;
  public static final int NOMBRE = 17;
  public static final int EOF = 0;
  public static final int PARAMETROS = 21;
  public static final int CORCHIZQ = 8;
  public static final int TEXTO = 22;
  public static final int CORCHDER = 9;
  public static final int error = 1;
  public static final int CLASES = 13;
  public static final int ENTERO = 2;
  public static final int DPUNTOS = 10;
  public static final int FUNCION = 19;
}

