/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package compi201503600.analisis.report;

import java_cup.runtime.*;
import java.io.Reader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>src/compi201503600/analisis/report/lexicoReporte.jflex</tt>
 */
public class ScannerLexReport implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;
  public static final int TEXTO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\2\1\4\1\5\1\3\22\0\1\14\1\30\1\70"+
    "\1\0\1\71\1\27\1\31\1\0\1\20\1\21\1\17\1\16\1\23"+
    "\1\10\1\24\1\13\1\1\1\60\1\61\1\62\1\63\1\64\1\65"+
    "\3\1\1\0\1\22\1\12\1\15\1\11\2\0\1\45\1\50\1\42"+
    "\1\53\1\34\1\67\1\66\1\56\1\47\2\6\1\40\1\52\1\51"+
    "\1\43\1\55\1\6\1\33\1\36\1\41\1\37\1\44\1\6\1\54"+
    "\1\57\1\6\1\25\1\0\1\26\1\0\1\7\1\0\1\45\1\50"+
    "\1\42\1\53\1\34\1\67\1\66\1\56\1\47\2\6\1\40\1\52"+
    "\1\51\1\43\1\55\1\6\1\33\1\36\1\41\1\37\1\44\1\6"+
    "\1\54\1\57\1\6\1\0\1\32\10\0\1\4\113\0\1\6\37\0"+
    "\1\6\76\0\2\46\115\0\1\35\u1ea8\0\1\4\1\4\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\2\1\2\5"+
    "\1\1\11\5\1\26\2\5\1\27\1\1\1\30\1\31"+
    "\1\32\1\0\1\33\1\34\1\35\1\36\1\0\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\2\5"+
    "\1\0\1\5\1\47\2\5\1\0\1\5\1\50\1\51"+
    "\5\5\1\52\4\5\1\0\2\5\1\53\2\5\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\5\1\62\1\63"+
    "\2\34\3\0\2\5\1\0\3\5\1\0\6\5\1\0"+
    "\6\5\2\64\1\0\4\5\3\0\2\5\1\0\3\5"+
    "\1\0\1\5\1\0\4\5\1\0\1\5\1\0\2\5"+
    "\1\65\2\5\1\0\1\5\1\0\1\5\1\66\1\67"+
    "\1\70\1\0\2\5\2\71\1\5\1\72\1\73\2\74"+
    "\1\0\1\5\1\75\1\5\1\0\1\5\1\0\1\5"+
    "\2\76\3\5\1\0\1\5\2\77\2\100\1\101\1\5"+
    "\2\102\1\5\1\0\1\5\1\0\2\5\1\103\1\5"+
    "\1\0\3\5\1\0\1\5\1\0\2\5\2\104\2\105"+
    "\1\5\1\106\2\107\1\0\1\5\1\110\1\111\2\112";

  private static int [] zzUnpackAction() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\164\0\256\0\164\0\164\0\350"+
    "\0\u0122\0\u015c\0\u0196\0\164\0\u01d0\0\u020a\0\u0244\0\164"+
    "\0\164\0\164\0\164\0\164\0\164\0\164\0\164\0\u027e"+
    "\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e"+
    "\0\u0488\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e"+
    "\0\u0658\0\164\0\u0692\0\164\0\164\0\164\0\u06cc\0\164"+
    "\0\u0706\0\164\0\164\0\u0740\0\164\0\164\0\164\0\164"+
    "\0\164\0\164\0\164\0\164\0\u077a\0\u07b4\0\u07ee\0\u0828"+
    "\0\350\0\u0862\0\u089c\0\u08d6\0\u0910\0\350\0\350\0\u094a"+
    "\0\u0984\0\u09be\0\u09f8\0\u0a32\0\350\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\350\0\u0c02\0\u0c3c\0\350"+
    "\0\350\0\350\0\350\0\350\0\350\0\u0c76\0\164\0\u06cc"+
    "\0\164\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c"+
    "\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc"+
    "\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac"+
    "\0\u11e6\0\164\0\350\0\u1220\0\u125a\0\u1294\0\u12ce\0\u1308"+
    "\0\u1342\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e\0\u14d8"+
    "\0\u1512\0\u154c\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e\0\u16a8"+
    "\0\u16e2\0\u171c\0\u1756\0\u1790\0\u17ca\0\350\0\u1804\0\u183e"+
    "\0\u1878\0\u18b2\0\u18ec\0\u1926\0\350\0\350\0\350\0\u1960"+
    "\0\u199a\0\u19d4\0\164\0\350\0\u1a0e\0\350\0\350\0\164"+
    "\0\350\0\u1a48\0\u1a82\0\350\0\u1abc\0\u1af6\0\u1b30\0\u1b6a"+
    "\0\u1ba4\0\164\0\350\0\u1bde\0\u1c18\0\u1c52\0\u1c8c\0\u1cc6"+
    "\0\164\0\350\0\164\0\350\0\350\0\u1d00\0\164\0\350"+
    "\0\u1d3a\0\u1d74\0\u1dae\0\u1de8\0\u1e22\0\u1e5c\0\350\0\u1e96"+
    "\0\u1ed0\0\u1f0a\0\u1f44\0\u1f7e\0\u1fb8\0\u1ff2\0\u202c\0\u2066"+
    "\0\u20a0\0\164\0\350\0\164\0\350\0\u20da\0\350\0\164"+
    "\0\350\0\u2114\0\u214e\0\350\0\350\0\164\0\350";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\0\1\7\1\10\1\4"+
    "\1\11\1\12\1\13\1\14\1\7\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\2\10"+
    "\1\37\1\40\1\10\1\41\1\42\1\4\1\10\1\43"+
    "\1\44\1\45\1\46\1\10\1\47\1\50\1\10\6\5"+
    "\1\10\1\51\1\52\1\53\2\54\1\55\65\54\1\56"+
    "\1\54\72\0\1\57\1\5\4\0\52\57\6\5\4\57"+
    "\1\0\1\10\4\0\2\10\23\0\2\10\1\0\10\10"+
    "\1\0\21\10\12\0\1\60\1\61\3\0\1\62\71\0"+
    "\1\63\67\0\1\64\1\0\1\65\71\0\1\66\71\0"+
    "\1\67\1\70\70\0\1\71\71\0\1\72\105\0\1\73"+
    "\72\0\1\74\40\0\1\10\4\0\2\10\23\0\1\10"+
    "\1\75\1\0\10\10\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\10\10\1\0\2\10\1\76"+
    "\16\10\44\0\1\77\30\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\0\4\10\1\100\3\10\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\1\101\1\102\1\0\7\10"+
    "\1\103\1\104\1\105\3\10\1\106\2\10\1\107\11\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\2\10"+
    "\1\110\2\10\1\111\1\10\1\112\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\0\7\10\1\113"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\2\10\1\114\5\10\1\0\21\10\3\0\1\10"+
    "\4\0\2\10\23\0\1\115\1\10\1\0\5\10\1\116"+
    "\2\10\1\0\21\10\3\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\0\5\10\1\117\2\10\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\1\10\1\120\1\0\10\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\1\10"+
    "\1\121\1\0\10\10\1\122\1\123\20\10\3\0\1\10"+
    "\4\0\2\10\23\0\1\124\1\10\1\0\10\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\1\125\1\126"+
    "\1\0\3\10\1\127\4\10\1\0\11\10\1\130\1\131"+
    "\1\132\1\133\1\134\1\135\2\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\5\10\1\136\2\10\1\0"+
    "\21\10\73\0\1\137\1\0\1\140\56\0\6\140\4\0"+
    "\2\61\1\141\1\142\66\61\13\143\1\144\56\143\1\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\145\1\146\7\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\3\10\1\147\4\10\1\0\21\10\45\0\1\150"+
    "\27\0\1\10\4\0\2\10\23\0\2\10\1\0\5\10"+
    "\1\151\2\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\10\10\1\0\5\10\1\152\13\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\10\10"+
    "\1\0\1\10\1\153\17\10\43\0\1\154\31\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\3\10\1\155\4\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\7\10\1\156\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\2\10\1\157\5\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\1\160\1\10"+
    "\1\0\10\10\1\0\2\10\1\161\16\10\3\0\1\10"+
    "\4\0\2\10\23\0\1\162\1\10\1\0\10\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\10\10\1\163\1\164\20\10\3\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\5\10\1\165\2\10\1\0\4\10"+
    "\1\166\14\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\10\10\1\0\3\10\1\167\15\10\3\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\3\10\1\170\4\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\4\10\1\171\3\10\1\0\21\10\46\0\1\172"+
    "\26\0\1\10\4\0\2\10\23\0\2\10\1\0\6\10"+
    "\1\173\1\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\10\10\1\174\1\175\20\10\3\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\0\7\10\1\176"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\10\10\1\0\3\10\1\177\15\10\3\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\10\10\1\0\2\10"+
    "\1\200\16\10\4\0\1\141\67\0\13\143\1\201\56\143"+
    "\13\0\1\202\115\0\1\203\33\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\1\10\1\204\6\10\1\0\21\10"+
    "\3\0\1\10\4\0\2\10\23\0\1\10\1\205\1\0"+
    "\10\10\1\0\21\10\35\0\1\206\37\0\1\10\4\0"+
    "\2\10\23\0\1\207\1\10\1\0\10\10\1\0\21\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\3\10"+
    "\1\210\4\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\2\10\1\211\5\10\1\0\21\10"+
    "\42\0\1\212\32\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\2\10\1\213\5\10\1\0\21\10\3\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\214\1\215\7\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\5\10\1\216\2\10\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\7\10\1\217\1\0\21\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\3\10"+
    "\1\220\4\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\10\10\1\221\1\222\20\10\70\0"+
    "\1\223\4\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\10\10\1\0\17\10\1\224\1\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\2\10\1\225\5\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\10\10\1\0\10\10\1\226\10\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\10\10\1\0\1\10\1\227"+
    "\17\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\5\10\1\230\2\10\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\10\10\1\231\1\232\20\10"+
    "\53\0\1\233\21\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\10\10\1\0\2\10\1\234\16\10\3\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\10\10\1\0\4\10"+
    "\1\235\14\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\2\10\1\236\5\10\1\0\21\10\3\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\3\10\1\237\4\10"+
    "\1\0\21\10\2\0\11\143\1\141\1\143\1\201\56\143"+
    "\11\0\1\141\1\0\1\202\116\0\1\240\32\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\2\10\1\241\5\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\1\242"+
    "\1\10\1\0\10\10\1\0\21\10\36\0\1\243\36\0"+
    "\1\10\4\0\2\10\23\0\1\10\1\244\1\0\10\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\4\10\1\245\1\246\2\10\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\1\10\1\247\1\0\10\10"+
    "\1\0\21\10\36\0\1\250\36\0\1\10\4\0\2\10"+
    "\23\0\1\10\1\251\1\0\10\10\1\0\21\10\36\0"+
    "\1\252\36\0\1\10\4\0\2\10\23\0\1\10\1\253"+
    "\1\0\10\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\1\254\1\10\1\0\10\10\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\0\4\10\1\255"+
    "\3\10\1\0\21\10\3\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\0\10\10\1\256\1\257\20\10\47\0\1\260"+
    "\25\0\1\10\4\0\2\10\23\0\2\10\1\0\7\10"+
    "\1\261\1\0\21\10\53\0\1\262\21\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\10\10\1\0\2\10\1\263"+
    "\16\10\3\0\1\10\4\0\2\10\23\0\1\10\1\264"+
    "\1\0\10\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\1\265\1\10\1\0\10\10\1\0\21\10\3\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\0\10\10\1\0"+
    "\4\10\1\266\14\10\54\0\1\267\20\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\10\10\1\0\3\10\1\270"+
    "\15\10\43\0\1\271\31\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\0\3\10\1\272\4\10\1\0\21\10\43\0"+
    "\1\273\31\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\3\10\1\274\4\10\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\2\10\1\0\5\10\1\275\2\10\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\5\10\1\276\2\10\1\0\21\10\37\0\2\277\34\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\277\1\300\7\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\3\10\1\301\4\10\1\0\21\10\55\0\1\302"+
    "\17\0\1\10\4\0\2\10\23\0\2\10\1\0\10\10"+
    "\1\0\4\10\1\303\14\10\52\0\1\304\22\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\10\10\1\0\1\10"+
    "\1\305\17\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\7\10\1\306\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\1\10\1\307\1\0\10\10\1\0\21\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\5\10"+
    "\1\310\2\10\1\0\21\10\47\0\1\311\25\0\1\10"+
    "\4\0\2\10\23\0\2\10\1\0\7\10\1\312\1\0"+
    "\21\10\3\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\2\10\1\313\5\10\1\0\21\10\3\0\1\10\4\0"+
    "\2\10\23\0\1\10\1\314\1\0\10\10\1\0\21\10"+
    "\47\0\1\315\25\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\7\10\1\316\1\0\21\10\42\0\1\317\32\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\0\2\10\1\320"+
    "\5\10\1\0\21\10\3\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\0\10\10\1\0\2\10\1\321\16\10\3\0"+
    "\1\10\4\0\2\10\23\0\2\10\1\322\1\323\7\10"+
    "\1\0\21\10\42\0\1\324\32\0\1\10\4\0\2\10"+
    "\23\0\2\10\1\0\2\10\1\325\5\10\1\0\21\10"+
    "\3\0\1\10\4\0\2\10\23\0\2\10\1\0\5\10"+
    "\1\326\2\10\1\0\21\10\3\0\1\10\4\0\2\10"+
    "\23\0\1\327\1\10\1\0\10\10\1\0\21\10\55\0"+
    "\1\330\17\0\1\10\4\0\2\10\23\0\2\10\1\0"+
    "\10\10\1\0\4\10\1\331\14\10\36\0\1\332\36\0"+
    "\1\10\4\0\2\10\23\0\1\10\1\333\1\0\10\10"+
    "\1\0\21\10\3\0\1\10\4\0\2\10\23\0\2\10"+
    "\1\0\5\10\1\334\2\10\1\0\21\10\3\0\1\10"+
    "\4\0\2\10\23\0\1\335\1\10\1\0\10\10\1\0"+
    "\21\10\37\0\2\336\34\0\1\10\4\0\2\10\23\0"+
    "\2\10\1\336\1\337\7\10\1\0\21\10\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8584];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\1\11\1\1\2\11\4\1\1\11\3\1"+
    "\10\11\22\1\1\11\1\1\3\11\1\0\1\11\1\1"+
    "\2\11\1\0\10\11\2\1\1\0\4\1\1\0\15\1"+
    "\1\0\14\1\1\11\1\1\1\11\1\1\3\0\2\1"+
    "\1\0\3\1\1\0\6\1\1\0\6\1\1\11\1\1"+
    "\1\0\4\1\3\0\2\1\1\0\3\1\1\0\1\1"+
    "\1\0\4\1\1\0\1\1\1\0\5\1\1\0\1\1"+
    "\1\0\4\1\1\0\2\1\1\11\4\1\1\11\1\1"+
    "\1\0\3\1\1\0\1\1\1\0\1\1\1\11\4\1"+
    "\1\0\1\1\1\11\1\1\1\11\3\1\1\11\2\1"+
    "\1\0\1\1\1\0\4\1\1\0\3\1\1\0\1\1"+
    "\1\0\2\1\1\11\1\1\1\11\3\1\1\11\1\1"+
    "\1\0\3\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    //Código de usuario
    String text = "";
    String strliteral = "";

    /*  Generamos un java_cup.Symbol para guardar el tipo de token 
        encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado 
       junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerLexReport(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ScannerLexReport(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 218) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return new Symbol(sym.TEXTOHTML, yyline, yycolumn, yytext());
          }
        case 75: break;
        case 2: 
          { return new Symbol(sym.ENTERO, yyline, yycolumn,yytext());
          }
        case 76: break;
        case 3: 
          { /*Saltos de linea, ignorados*/
          }
        case 77: break;
        case 4: 
          { /*Espacios en blanco, ignorados*/
          }
        case 78: break;
        case 5: 
          { return new Symbol(sym.ID, yyline, yycolumn,yytext());
          }
        case 79: break;
        case 6: 
          { return new Symbol(sym.OPRESTA, yyline, yycolumn, yytext());
          }
        case 80: break;
        case 7: 
          { return new Symbol(sym.OPMAY, yyline, yycolumn, yytext());
          }
        case 81: break;
        case 8: 
          { return new Symbol(sym.OPMEN, yyline, yycolumn, yytext());
          }
        case 82: break;
        case 9: 
          { return new Symbol(sym.OPDIV, yyline, yycolumn, yytext());
          }
        case 83: break;
        case 10: 
          { return new Symbol(sym.OPIGUAL, yyline, yycolumn, yytext());
          }
        case 84: break;
        case 11: 
          { return new Symbol(sym.OPSUMA, yyline, yycolumn, yytext());
          }
        case 85: break;
        case 12: 
          { return new Symbol(sym.OPMULT, yyline, yycolumn, yytext());
          }
        case 86: break;
        case 13: 
          { return new Symbol(sym.PARA, yyline, yycolumn, yytext());
          }
        case 87: break;
        case 14: 
          { return new Symbol(sym.PARC, yyline, yycolumn, yytext());
          }
        case 88: break;
        case 15: 
          { return new Symbol(sym.PCOMA, yyline, yycolumn, yytext());
          }
        case 89: break;
        case 16: 
          { return new Symbol(sym.COMA, yyline, yycolumn, yytext());
          }
        case 90: break;
        case 17: 
          { return new Symbol(sym.PUNTO, yyline, yycolumn, yytext());
          }
        case 91: break;
        case 18: 
          { return new Symbol(sym.CORA, yyline, yycolumn, yytext());
          }
        case 92: break;
        case 19: 
          { return new Symbol(sym.CORC, yyline, yycolumn, yytext());
          }
        case 93: break;
        case 20: 
          { return new Symbol(sym.OPMODULO, yyline, yycolumn, yytext());
          }
        case 94: break;
        case 21: 
          { return new Symbol(sym.OPNOT, yyline, yycolumn, yytext());
          }
        case 95: break;
        case 22: 
          { return new Symbol(sym.P, yyline, yycolumn, yytext());
          }
        case 96: break;
        case 23: 
          { yybegin(CADENA); text = "\"";
          }
        case 97: break;
        case 24: 
          { text += yytext();
          }
        case 98: break;
        case 25: 
          { String tmp = text; 
                    text = "";  
                    yybegin(YYINITIAL);
                    return new Symbol(sym.TEXTOHTML, yychar, yyline, tmp);
          }
        case 99: break;
        case 26: 
          { String tmp = text + "\""; 
                    text = ""; 
                    yybegin(YYINITIAL);  
                    return new Symbol(sym.CADENA, yychar,yyline,tmp);
          }
        case 100: break;
        case 27: 
          { return new Symbol(sym.OPDECREMENT, yyline, yycolumn, yytext());
          }
        case 101: break;
        case 28: 
          { /* Comentarios ignorados */
          }
        case 102: break;
        case 29: 
          { return new Symbol(sym.OPASIGRESTA, yyline, yycolumn, yytext());
          }
        case 103: break;
        case 30: 
          { return new Symbol(sym.OPMAYIGUAL, yyline, yycolumn, yytext());
          }
        case 104: break;
        case 31: 
          { return new Symbol(sym.OPMENIGUAL, yyline, yycolumn, yytext());
          }
        case 105: break;
        case 32: 
          { return new Symbol(sym.OPCOMPARADOR, yyline, yycolumn, yytext());
          }
        case 106: break;
        case 33: 
          { return new Symbol(sym.OPASIGSUMA, yyline, yycolumn, yytext());
          }
        case 107: break;
        case 34: 
          { return new Symbol(sym.OPINCREMENT, yyline, yycolumn, yytext());
          }
        case 108: break;
        case 35: 
          { return new Symbol(sym.OPASIGMULT, yyline, yycolumn, yytext());
          }
        case 109: break;
        case 36: 
          { return new Symbol(sym.OPDISTINTO, yyline, yycolumn, yytext());
          }
        case 110: break;
        case 37: 
          { return new Symbol(sym.OPAND, yyline, yycolumn, yytext());
          }
        case 111: break;
        case 38: 
          { return new Symbol(sym.OPOR, yyline, yycolumn, yytext());
          }
        case 112: break;
        case 39: 
          { return new Symbol(sym.TR, yyline, yycolumn, yytext());
          }
        case 113: break;
        case 40: 
          { return new Symbol(sym.TD, yyline, yycolumn, yytext());
          }
        case 114: break;
        case 41: 
          { return new Symbol(sym.TH, yyline, yycolumn, yytext());
          }
        case 115: break;
        case 42: 
          { return new Symbol(sym.BR, yyline, yycolumn, yytext());
          }
        case 116: break;
        case 43: 
          { return new Symbol(sym.HR, yyline, yycolumn, yytext());
          }
        case 117: break;
        case 44: 
          { return new Symbol(sym.H1, yyline, yycolumn, yytext());
          }
        case 118: break;
        case 45: 
          { return new Symbol(sym.H2, yyline, yycolumn, yytext());
          }
        case 119: break;
        case 46: 
          { return new Symbol(sym.H3, yyline, yycolumn, yytext());
          }
        case 120: break;
        case 47: 
          { return new Symbol(sym.H4, yyline, yycolumn, yytext());
          }
        case 121: break;
        case 48: 
          { return new Symbol(sym.H5, yyline, yycolumn, yytext());
          }
        case 122: break;
        case 49: 
          { return new Symbol(sym.H6, yyline, yycolumn, yytext());
          }
        case 123: break;
        case 50: 
          { return new Symbol(sym.DOLLAR, yyline, yycolumn, yytext());
          }
        case 124: break;
        case 51: 
          { return new Symbol(sym.DECIMAL, yyline, yycolumn, yytext());
          }
        case 125: break;
        case 52: 
          { return new Symbol(sym.DIV, yyline, yycolumn, yytext());
          }
        case 126: break;
        case 53: 
          { return new Symbol(sym.BODY, yyline, yycolumn, yytext());
          }
        case 127: break;
        case 54: 
          { return new Symbol(sym.HEAD, yyline, yycolumn, yytext());
          }
        case 128: break;
        case 55: 
          { return new Symbol(sym.HTML, yyline, yycolumn, yytext());
          }
        case 129: break;
        case 56: 
          { return new Symbol(sym.FONT, yyline, yycolumn, yytext());
          }
        case 130: break;
        case 57: 
          { return new Symbol(sym.SCORE, yyline, yycolumn, yytext());
          }
        case 131: break;
        case 58: 
          { return new Symbol(sym.TSTRING, yyline, yycolumn, yytext());
          }
        case 132: break;
        case 59: 
          { return new Symbol(sym.TABLE, yyline, yycolumn, yytext());
          }
        case 133: break;
        case 60: 
          { return new Symbol(sym.TITLE, yyline, yycolumn, yytext());
          }
        case 134: break;
        case 61: 
          { return new Symbol(sym.COLOR, yyline, yycolumn, yytext());
          }
        case 135: break;
        case 62: 
          { return new Symbol(sym.ALIGN, yyline, yycolumn, yytext());
          }
        case 136: break;
        case 63: 
          { return new Symbol(sym.PRINT, yyline, yycolumn, yytext());
          }
        case 137: break;
        case 64: 
          { return new Symbol(sym.RESULT, yyline, yycolumn, yytext());
          }
        case 138: break;
        case 65: 
          { return new Symbol(sym.TINT, yyline, yycolumn, yytext());
          }
        case 139: break;
        case 66: 
          { return new Symbol(sym.CLASES, yyline, yycolumn, yytext());
          }
        case 140: break;
        case 67: 
          { return new Symbol(sym.NOMBRE, yyline, yycolumn, yytext());
          }
        case 141: break;
        case 68: 
          { return new Symbol(sym.METODOS, yyline, yycolumn, yytext());
          }
        case 142: break;
        case 69: 
          { return new Symbol(sym.TDOUBLE, yyline, yycolumn, yytext());
          }
        case 143: break;
        case 70: 
          { return new Symbol(sym.TCHAR, yyline, yycolumn, yytext());
          }
        case 144: break;
        case 71: 
          { return new Symbol(sym.CANTIDAD, yyline, yycolumn, yytext());
          }
        case 145: break;
        case 72: 
          { return new Symbol(sym.TBOOL, yyline, yycolumn, yytext());
          }
        case 146: break;
        case 73: 
          { return new Symbol(sym.TEXTCOLOR, yyline, yycolumn, yytext());
          }
        case 147: break;
        case 74: 
          { return new Symbol(sym.VARIABLES, yyline, yycolumn, yytext());
          }
        case 148: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
