
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 29 16:14:48 CST 2018
//----------------------------------------------------

package compi201503600.analisis.report;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TEXTOHTML = 67;
  public static final int TSTRING = 39;
  public static final int TCHAR = 38;
  public static final int OPASIGMULT = 5;
  public static final int NOMBRE = 32;
  public static final int ENTERO = 42;
  public static final int P = 60;
  public static final int OPMAY = 21;
  public static final int SCORE = 30;
  public static final int OPINCREMENT = 6;
  public static final int FONT = 66;
  public static final int OPMENIGUAL = 22;
  public static final int OPASIGRESTA = 4;
  public static final int OPSUMA = 15;
  public static final int TBOOL = 40;
  public static final int OPDECREMENT = 7;
  public static final int TEXTCOLOR = 64;
  public static final int DIV = 59;
  public static final int TDOUBLE = 37;
  public static final int CLASES = 34;
  public static final int OPASIGSUMA = 3;
  public static final int ID = 44;
  public static final int DECIMAL = 43;
  public static final int EOF = 0;
  public static final int OPDISTINTO = 25;
  public static final int TABLE = 55;
  public static final int OPNOT = 28;
  public static final int OPAND = 26;
  public static final int OPOR = 27;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 68;
  public static final int OPCOMPARADOR = 24;
  public static final int BR = 61;
  public static final int OPDIV = 18;
  public static final int HR = 62;
  public static final int HEAD = 46;
  public static final int COLOR = 63;
  public static final int PCOMA = 12;
  public static final int OPRESTA = 16;
  public static final int TINT = 36;
  public static final int METODOS = 35;
  public static final int TR = 58;
  public static final int TITLE = 48;
  public static final int VARIABLES = 31;
  public static final int PUNTO = 14;
  public static final int DOLLAR = 69;
  public static final int OPIGUAL = 2;
  public static final int BODY = 47;
  public static final int TH = 56;
  public static final int CANTIDAD = 33;
  public static final int PARC = 9;
  public static final int TD = 57;
  public static final int PARA = 8;
  public static final int CORC = 11;
  public static final int HTML = 45;
  public static final int CORA = 10;
  public static final int H6 = 54;
  public static final int OPMAYIGUAL = 23;
  public static final int H5 = 53;
  public static final int OPMODULO = 19;
  public static final int H4 = 52;
  public static final int ALIGN = 65;
  public static final int H3 = 51;
  public static final int OPMULT = 17;
  public static final int OPMEN = 20;
  public static final int H2 = 50;
  public static final int PRINT = 41;
  public static final int H1 = 49;
  public static final int RESULT = 29;
}

