
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 04 09:17:42 CST 2018
//----------------------------------------------------

package compi201503600.analisis.report;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TD = 59;
  public static final int H6 = 56;
  public static final int H5 = 55;
  public static final int H4 = 54;
  public static final int H3 = 53;
  public static final int H2 = 52;
  public static final int H1 = 51;
  public static final int OPMODULO = 24;
  public static final int TABLE = 57;
  public static final int OPDECREMENT = 12;
  public static final int OPAND = 31;
  public static final int OPMEN = 25;
  public static final int OPRESTA = 21;
  public static final int TBOOL = 45;
  public static final int TDOUBLE = 42;
  public static final int FONT = 68;
  public static final int PARAMETRO = 73;
  public static final int FUNCION = 71;
  public static final int OPOR = 32;
  public static final int HTML = 47;
  public static final int PCOMA = 17;
  public static final int PARC = 14;
  public static final int OPASIGMULT = 10;
  public static final int PARA = 13;
  public static final int DOLLAR = 69;
  public static final int COMA = 18;
  public static final int ENTERO = 5;
  public static final int TEXTOHTML = 2;
  public static final int CLASE = 72;
  public static final int RESULT = 34;
  public static final int OPASIGSUMA = 8;
  public static final int OPNOT = 33;
  public static final int TIPO = 70;
  public static final int ALIGN = 67;
  public static final int DECIMAL = 6;
  public static final int NOMBRE = 37;
  public static final int OPASIGRESTA = 9;
  public static final int DIV = 61;
  public static final int OPMENIGUAL = 27;
  public static final int OPDISTINTO = 30;
  public static final int P = 62;
  public static final int CORC = 16;
  public static final int CORA = 15;
  public static final int OPCOMPARADOR = 29;
  public static final int EOF = 0;
  public static final int PUNTO = 19;
  public static final int CLASES = 39;
  public static final int PRINT = 46;
  public static final int OPINCREMENT = 11;
  public static final int TCHAR = 43;
  public static final int BODY = 49;
  public static final int TITLE = 50;
  public static final int error = 1;
  public static final int OPDIV = 23;
  public static final int OPMAY = 26;
  public static final int OPMULT = 22;
  public static final int ID = 4;
  public static final int COLOR = 65;
  public static final int TINT = 41;
  public static final int HEAD = 48;
  public static final int TEXTCOLOR = 66;
  public static final int VARIABLES = 36;
  public static final int BR = 63;
  public static final int CANTIDAD = 38;
  public static final int OPSUMA = 20;
  public static final int HR = 64;
  public static final int CADENA = 3;
  public static final int OPIGUAL = 7;
  public static final int METODOS = 40;
  public static final int OPMAYIGUAL = 28;
  public static final int TR = 60;
  public static final int SCORE = 35;
  public static final int TH = 58;
  public static final int TSTRING = 44;
}

